package main

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/mrktsm/gedis/internal/server"
)

func main() {
	if err := writeCommandTable(os.Stdout, server.NewEngine().Commands()); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "generate command table: %v\n", err)
		os.Exit(1)
	}
}

func writeCommandTable(output io.Writer, commands []server.CommandMetadata) error {
	_, err := io.WriteString(output, renderCommandTable(commands))
	return err
}

func renderCommandTable(commands []server.CommandMetadata) string {
	commands = append([]server.CommandMetadata(nil), commands...)
	sort.Slice(commands, func(first, second int) bool {
		if commands[first].Group == commands[second].Group {
			return commands[first].Name < commands[second].Name
		}
		return commands[first].Group < commands[second].Group
	})

	var table strings.Builder
	table.WriteString("<!-- Code generated by go run ./cmd/gedis-command-docs; DO NOT EDIT. -->\n\n")
	table.WriteString("# Command compatibility\n\n")
	fmt.Fprintf(
		&table,
		"Gedis currently exposes %d top-level engine commands over RESP2. This table is generated from the same registry used for dispatch and `COMMAND`; each syntax lists only options implemented by Gedis.\n\n",
		len(commands),
	)
	table.WriteString("| Group | Command | Supported syntax | Arity | Flags | Key positions (first/last/step) |\n")
	table.WriteString("| --- | --- | --- | ---: | --- | --- |\n")
	for _, command := range commands {
		flags := "—"
		if len(command.Flags) > 0 {
			flags = strings.Join(command.Flags, ", ")
		}
		keys := "—"
		if command.FirstKey != 0 {
			keys = fmt.Sprintf("%d / %d / %d", command.FirstKey, command.LastKey, command.KeyStep)
		}
		fmt.Fprintf(
			&table,
			"| %s | `%s` | `%s` | %s | %s | %s |\n",
			escapeCell(command.Group),
			strings.ToUpper(command.Name),
			escapeCell(command.Syntax),
			strconv.Itoa(command.Arity),
			escapeCell(flags),
			keys,
		)
	}
	table.WriteString("\nA negative arity is the minimum accepted argument count, including the command name. Key positions use Redis's legacy first/last/step convention; `-1` means the final argument.\n\n")
	table.WriteString("`REPLCONF` and `PSYNC` are connection-layer replication handshake commands, so they are tested and documented separately and are not included in the engine registry or `COMMAND COUNT`.\n\n")
	table.WriteString("## Regression evidence\n\n")
	table.WriteString("- Connection, discovery, and server commands: `internal/server/engine_test.go`, `command_info_test.go`, `info_test.go`, and `server_test.go`.\n")
	table.WriteString("- Strings, generic keys, and expiration: `internal/server/strings_test.go` and `internal/store/keyspace_test.go`.\n")
	table.WriteString("- Sorted sets: `internal/server/sorted_sets_test.go`, `internal/store/sorted_set_test.go`, and randomized indexed-skip-list tests.\n")
	table.WriteString("- Persistence: `internal/server/persistence_test.go`, `internal/aof`, and startup recovery tests under `cmd/gedis`.\n")
	table.WriteString("\nSee the [conformance log](conformance.md) for the Redis 7.2.7 probe method and explicit compatibility boundaries.\n")
	return table.String()
}

func escapeCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
